var Slider = {
  "propTypes": {
    "min": {},
    "max": {},
    "step": {},
    "defaultValue": {},
    "value": {},
    "marks": {},
    "included": {},
    "className": {},
    "prefixCls": {},
    "tooltipPrefixCls": {},
    "disabled": {},
    "children": {},
    "onBeforeChange": function () {},
    "onChange": function () {},
    "onAfterChange": function () {},
    "handle": {},
    "tipTransitionName": {},
    "tipFormatter": {},
    "dots": {},
    "range": {},
    "vertical": {},
    "allowCross": {},
    "pushable": {}
  },
  "defaultProps": {
    "prefixCls": {},
    "className": {},
    "tipTransitionName": {},
    "min": {},
    "max": {},
    "step": {},
    "marks": {},
    "handle": {},
    "onBeforeChange": function () {},
    "onChange": function () {},
    "onAfterChange": function () {},
    "tipFormatter": {},
    "included": {},
    "disabled": {},
    "dots": {},
    "range": {},
    "vertical": {},
    "allowCross": {},
    "pushable": {}
  }
}
